services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gamestore-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=GameStore123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data:
