services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gamestore-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=GameStore123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P GameStore123! -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
  gamestore-api:
    build:
      context: .
      dockerfile: EpamKse.GameStore.Api/Dockerfile
    env_file:
      - EpamKse.GameStore.Api/.env
    ports:
      - "5186:5186"
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped

  gamestore-payment-service:
    build:
      context: .
      dockerfile: EpamKse.GameStore.PaymentService/Dockerfile
    env_file:
      - EpamKse.GameStore.PaymentService/.env
    ports:
      - "5172:5172"
    restart: unless-stopped

volumes:
  sqlserver_data:
