services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gamestore-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=GameStore123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    
  gamestore-api:
    image: gamestore-api
    build:
      context: .
      dockerfile: EpamKse.GameStore.Api/Dockerfile
    env_file:
      - EpamKse.GameStore.Api/.env
    ports:
      - "5186:5186"

  gamestore-payment-service:
    image: gamestore-payment-service
    build:
      context: .
      dockerfile: EpamKse.GameStore.PaymentService/Dockerfile
    env_file:
      - EpamKse.GameStore.PaymentService/.env
    ports:
      - "5172:5172"

volumes:
  sqlserver_data:
  

